// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhshhm-Nf_-JNRKARy1PgPbv17IRD2vjg',
    appId: '1:886596742928:web:02945ba5381b91b9413f95',
    messagingSenderId: '886596742928',
    projectId: 'taskapp-willsoar',
    authDomain: 'taskapp-willsoar.firebaseapp.com',
    storageBucket: 'taskapp-willsoar.firebasestorage.app',
    measurementId: 'G-150S1HBNEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwCpKvUyXAGv13TX9fDP_14Czsyc_Y8P4',
    appId: '1:886596742928:android:fbd4af91d9c891ab413f95',
    messagingSenderId: '886596742928',
    projectId: 'taskapp-willsoar',
    storageBucket: 'taskapp-willsoar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo7PESQf0jT9-YUze6EGBFH0q5DbufPXE',
    appId: '1:886596742928:ios:4ef2ae9a6b27ba41413f95',
    messagingSenderId: '886596742928',
    projectId: 'taskapp-willsoar',
    storageBucket: 'taskapp-willsoar.firebasestorage.app',
    iosBundleId: 'com.example.taskmanagementFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo7PESQf0jT9-YUze6EGBFH0q5DbufPXE',
    appId: '1:886596742928:ios:4ef2ae9a6b27ba41413f95',
    messagingSenderId: '886596742928',
    projectId: 'taskapp-willsoar',
    storageBucket: 'taskapp-willsoar.firebasestorage.app',
    iosBundleId: 'com.example.taskmanagementFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhshhm-Nf_-JNRKARy1PgPbv17IRD2vjg',
    appId: '1:886596742928:web:6d228414140a9983413f95',
    messagingSenderId: '886596742928',
    projectId: 'taskapp-willsoar',
    authDomain: 'taskapp-willsoar.firebaseapp.com',
    storageBucket: 'taskapp-willsoar.firebasestorage.app',
    measurementId: 'G-DBE1VHQ586',
  );
}
